#!/usr/bin/env sh

SUFFIX=$1

if [ -z "${SUFFIX}" ]; then
  ./gradlew publish \
      -Psigning.secretKeyRingFile=secring.gpg \
      -Psigning.password="${SIGNING_PASS}" \
      -Psigning.keyId="${SIGNING_KEY_ID}" \
      --stacktrace
else
  ./gradlew publish \
      -PversionSuffix="${SUFFIX}" \
      -Psigning.secretKeyRingFile=secring.gpg \
      -Psigning.password="${SIGNING_PASS}" \
      -Psigning.keyId="${SIGNING_KEY_ID}" \
      --stacktrace
fi