# Release build with upload to OSSRH

name: Release

on:
  release:
    types: [prereleased, released]

jobs:

  gradleValidation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

  release:
    name: Publish To Maven Central
    needs: gradleValidation
    runs-on: macos-13
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Decrypt Key Ring File
        env:
          SIGNING_KEY_FILE_PASSPHRASE: ${{ secrets.signingKeyFilePassphrase }}
        run: .github/scripts/decrypt_secring
      - name: Publish To Maven Central
        env:
          SIGNING_KEY_ID: ${{ secrets.signingKeyId }}
          SIGNING_PASS: ${{ secrets.signingPassword }}
          SONATYPE_USERNAME: ${{ secrets.ossrhUsername }}
          SONATYPE_PASSWORD: ${{ secrets.ossrhPassword }}
        run: .github/scripts/publish_artifacts

  changelog:
    name: Update Changelog
    needs: release
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Patch Changelog
        run: ./gradlew patchChangelog
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update changelog" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
