# Artifacts upload for releases

name: Release

on:
  release:
    types: [prereleased, released]

jobs:

  release:

    name: Upload To Maven Central
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

      - name: Checkout Tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decrypt Key Ring File
        env:
          SIGNING_KEY_FILE_PASSPHRASE: ${{ secrets.signingKeyFilePassphrase }}
        run: .github/scripts/decrypt_secring

      - name: Upload To Maven Central
        env:
          SIGNING_KEY_ID: ${{ secrets.signingKeyId }}
          SIGNING_PASS: ${{ secrets.signingPassword }}
          SONATYPE_USERNAME: ${{ secrets.ossrhUsername }}
          SONATYPE_PASSWORD: ${{ secrets.ossrhPassword }}
        run: .github/scripts/publish_artifacts ${{ matrix.os }}
