# SNAPSHOT artifacts upload for every commit on develop branch

name: Snapshot Release

on:
  push:
    branches: [develop]

jobs:

  snapshotRelease:

    name: Publish To OSSRH Snapshot Repository
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decrypt Key Ring File
        env:
          SIGNING_KEY_FILE_PASSPHRASE: ${{ secrets.signingKeyFilePassphrase }}
        run: |
          gpg --quiet --batch --yes --decrypt \
            --passphrase="${SIGNING_KEY_FILE_PASSPHRASE}" \
            --output secring.gpg secring.gpg.gpg

      - name: Publish To OSSRH Snapshot Repository
        env:
          SIGNING_KEY_ID: ${{ secrets.signingKeyId }}
          SIGNING_PASS: ${{ secrets.signingPassword }}
          SONATYPE_USERNAME: ${{ secrets.ossrhUsername }}
          SONATYPE_PASSWORD: ${{ secrets.ossrhPassword }}
        run: |
          ./gradlew publish \
            -Psigning.secretKeyRingFile=secring.gpg \
            -Psigning.password="${SIGNING_PASS}" \
            -Psigning.keyId="${SIGNING_KEY_ID}"
