# SNAPSHOT artifacts upload for every commit on develop branch

name: Snapshot Release

on:
  push:
    branches: [develop]

jobs:

  snapshotRelease:

    name: Publish To OSSRH Snapshot Repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8

      - name: Decrypt Key Ring File
        env:
          SIGNING_KEY_FILE_PASSPHRASE: ${{ secrets.signingKeyFilePassphrase }}
        run: .github/scripts/decrypt_secring

      - name: Publish To OSSRH Snapshot Repository
        env:
          SIGNING_KEY_ID: ${{ secrets.signingKeyId }}
          SIGNING_PASS: ${{ secrets.signingPassword }}
          SONATYPE_USERNAME: ${{ secrets.ossrhUsername }}
          SONATYPE_PASSWORD: ${{ secrets.ossrhPassword }}
        run: .github/scripts/publish_artifacts ${{ matrix.os }}
